AWSTemplateFormatVersion: '2010-09-09'
Description: Create an S3 bucket with versioning enabled

Resources:
  MyS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: cfs3buck6453443
      VersioningConfiguration:
        Status: Enabled

Outputs:
  BucketName:
    Description: Name of the created S3 bucket
    Value: !Ref MyS3Bucket
